### PR TITLE
Add 2 recent examples

### PR DESCRIPTION
**Pull request by mgold**
Adds two recent examples to the yaml file, and images for them. Unfortunately I wasn't able to get the yaml file to compile under `json2yaml@1.0.3` and `yaml@0.2.3` or `0.3`.

I did manage to get Babel running and documented it, but because I'm not changing the website I didn't commit the change (it seems to be using ES6 features, which means finding the right flag to pass in to turn them off). If you want to open this up to more people and really hammer out the build process, I can help with that. Otherwise, run whatever magic is working on your machine and push up the new version with the additions.

Cheers!

### CODE REVIEW

**Comment by joshuahhh** [comment]
Thanks for the PR!

I'm on a new computer since last building the site, and I can't get the YAML to compile either. Awkward. Once I get that working again, I'll merge this. (And in the short or long run, I would like to switch to an NPM/webpack-based build system.)

**Comment by mgold** [comment]
Okay, sounds good!

**Comment by joshuahhh** [comment]
OK @mgold – I've tightened up the dependency/build system. Would you mind testing it out by pulling the changes and updating this PR?

To be clear: I think this PR should only need to include changes to `src/data.yaml` and `index.js[.map]` (which now includes compiled YAML).

Thanks!

**Comment by mgold** [comment]
@joshuahhh Works like a charm, except the server is on port 3000 not port 3333 as the README says.

Force-pushed revised contributions. They change on the files you say, plus new images.

**Pull request merged**
